# Generated by Django 4.2.3 on 2023-08-01 11:40

import dj_dynamic_templates.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('code', models.PositiveBigIntegerField(editable=False)),
                ('app_name', models.CharField(help_text='Enter the App name to save template in that folder', max_length=50, validators=[dj_dynamic_templates.validators.validate_app])),
                ('name', models.CharField(help_text='With this name an folder will be created in this App', max_length=50)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dj Dynamic Templates  Category',
                'verbose_name_plural': 'Dj Dynamic Templates  Category',
                'db_table': 'dj_dynamic_templates__category',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.PositiveBigIntegerField(editable=False)),
                ('body_content', markdownx.models.MarkdownxField()),
                ('style_content', models.TextField(blank=True)),
                ('script_content', models.TextField(blank=True)),
                ('name', models.CharField(help_text='Entered name will treated as template file name, A template file is created with this file name', max_length=50)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(help_text='Select the category where you want to save the template', on_delete=django.db.models.deletion.CASCADE, related_name='mail_template_category', to='dj_dynamic_templates.category')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ddt_mail_template_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('parent_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dj_dynamic_templates.mailtemplate')),
            ],
            options={
                'verbose_name': 'Dj Dynamic Templates  Mail Template',
                'verbose_name_plural': "Dj Dynamic Templates  Mail Template's",
                'db_table': 'dj_dynamic_templates__mail_template',
                'managed': True,
            },
        ),
    ]
